name:                project-template
version:             0.1.0.0
github:              "unknown/unknown"
license:             BSD3
author:              "urbanizzz"
maintainer:          "yuraoskin@gmail.com"
copyright:           "urbanizzz"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README

dependencies:
- base >= 4.7 && < 5
- text
- QuickCheck
- yaml

# ghc-options:
# - -Wall
# - -Werror
# - -Wcompat
# - -Wincomplete-uni-patterns

library:
  source-dirs: src

executables:
  project-template-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - project-template

tests:
  project-template-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - project-template

